# Generated by Django 3.2.9 on 2023-11-18 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('burger', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TeacherProfile',
        ),
    ]
